#!/bin/bash

#Create files in dirs for testing


DIR=$1

COUNTER=0
while [ $COUNTER -lt 100 ]; do
echo The counter is $COUNTER
echo 'aasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslasldkfjsldkfja;sldkfjsldkfjsldkfjaslsldkfjsldkfja;sldkfjsldkfjsldkfjasldkfj' > $DIR/file$COUNTER.txt

let COUNTER=COUNTER+1
done


